FROM node:10-alpine
MAINTAINER simon-martin-it
COPY . .
RUN apk update
RUN apk add git
RUN apk add python3
RUN apk add py3-pip
RUN git clone https://github.com/simon-martin-it/DB-Advanced.git
RUN cd DB-Advanced/Docker
RUN pip3 install -r req.txt
CMD ["python3", "scraper.py"]
